# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5cbb25658f739d5870e987f8c842adc142e7f282b0ebfac13dc684297dfb76aa2ef8459f3d2938a08fc560702d7e4bbcdd7df5ac578858308603227ba63c133

test:
  secret_key_base: b849e2232d874fa2c186adbad8d1f1b22f45ad3c9eacc5f3d928c581b924050b8d102f2eea4eb94400c514bfc49c301c07dcc5692afcaebc95b8dd0bc36f48d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
